
import _Button from './Button';
import _Filter from './Filter';
import _Tabs from './Tabs';
import _Confirm from './Confirm';
import _ForceConfirm from './ForceConfirm';
import _Modal from './Modal';
import _Input from './Input';
import _Select from './Select';
import _Radio from './Radio';
import _DatePicker from './DatePicker';
import _message from './Message';
import _Tree from './Tree';
import _Table from './table';
import _Pagination from './Pagination';
import _ModalAside from './ModalAside';
import _FormText from './Form/Text';
import _CheckBox from './Checkbox';
import * as _NestedTable from './NestedTable';
import _Icon from './Icon';
import _Switch from './Switch';
import _TimePicker from './TimePicker';
import _Spin from './Spin';
import _Tag from './Tag';
import _DuckyPage from './DuckyPage';
import _Popover from './Popover';
import _Popconfirm from './Popconfirm';

export const Button = _Button;
export const Filter = _Filter;
export const Tabs = _Tabs;
export const Confirm = _Confirm;
export const Modal = _Modal;
export const Input = _Input;
export const Select = _Select;
export const Radio = _Radio;
export const DatePicker = _DatePicker;
export const message = _message;
export const Tree = _Tree;
export const Table = _Table;
export const Pagination = _Pagination;
export const ModalAside = _ModalAside;
export const FormText = _FormText;
export const NestedTable = _NestedTable;
export const Checkbox = _CheckBox;
export const Icon = _Icon;
export const Switch = _Switch;
export const TimePicker = _TimePicker;
export const Spin = _Spin;
export const Tag = _Tag;
export const DuckyPage = _DuckyPage;
export const Popover = _Popover;
export const Popconfirm = _Popconfirm;
export const ForceConfirm = _ForceConfirm;
