stages:
  - install
  - deploy


cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/


# 安装依赖
install_dev:
  stage: install
  only:
    - 'deploy-dev'
  tags:
    - '153'
  script:
    - npm install

install_test:
  stage: install
  only:
    - 'deploy-test'
  tags:
    - '76'
  script:
    - npm install


# 环境部署
deploy_dev:
  stage: deploy
  only:
    - 'deploy-dev'
  tags:
    - '153'
  script:
    - pm2 delete 16001-dva-cd-dev || true
    - pm2 start engine/pm2-dev.json

deploy_test:
  stage: deploy
  only:
    - 'deploy-test'
  tags:
    - '76'
  script:
    - pm2 delete 16001-dva-cd-test || true
    - pm2 start engine/pm2-test.json
